salutation: Hello!
logging:
  level: INFO
server:
  applicationConnector:
    - scheme: HTTPS
      port: 8009
      cert: server.crt
      key: server.key
    - scheme: HTTP
      port: 8007
  adminConnector:
    - scheme: HTTP
      port: 8010
